 --도시발전 _신희철
 
 SELECT :SIDO, :SIGUNGU,
 NVL((((SELECT COUNT(STORECATEGORY)
FROM BURGERSTORE
WHERE SIDO = :SIDO
 AND SIGUNGU= :SIGUNGU
 AND STORECATEGORY='BURGER KING'
 GROUP BY STORECATEGORY)+
 (SELECT COUNT(STORECATEGORY)
FROM BURGERSTORE
WHERE SIDO = :SIDO
 AND SIGUNGU= :SIGUNGU
 AND STORECATEGORY='MACDONALD'
 GROUP BY STORECATEGORY)+
 (SELECT COUNT(STORECATEGORY)
FROM BURGERSTORE
WHERE SIDO = :SIDO
 AND SIGUNGU= :SIGUNGU
 AND STORECATEGORY='KFC'
 GROUP BY STORECATEGORY))
 /(SELECT COUNT(STORECATEGORY)
FROM BURGERSTORE
WHERE SIDO = :SIDO
 AND SIGUNGU= :SIGUNGU
 AND STORECATEGORY='LOTTERIA'
 GROUP BY STORECATEGORY)),0) AS 도시발전지수
 FROM BURGERSTORE
 GROUP BY :SIDO, :SIGUNGU;
 
 
 
 
 
 
 